CREATE DATABASE OrnekDB;

CREATE TABLE OGRENCILER(
--KOLON_ADI KOLON_TURU KOLON_KISITLAYICILARI

ID INT PRIMARY KEY IDENTITY,
ADI NVARCHAR(25) NOT NULL,
SOYADI NVARCHAR(25) NOT NULL,
OGRENCINO CHAR(8) NOT NULL,
DOGUMTARIHI DATE NOT NULL,
DOGUMYERI NVARCHAR(25) NOT NULL,
ANNEADI NVARCHAR(25) NULL,
BABAADI NVARCHAR(25) NULL,
DURUMU BIT NOT NULL
)


INSERT INTO OGRENCILER
VALUES('Burak','Gonca','12665789','1991-02-05',
'CANKAYA',NULL,NULL,1)
GO

SELECT * FROM OGRENCILER

INSERT INTO OGRENCILER(ADI,SOYADI,OGRENCINO,DOGUMTARIHI,DOGUMYERI,DURUMU)
VALUES('OGRENCI1','SOYISIM1','4559789','1980-04-28','KECIOREN',0)
GO

ALTER TABLE OGRENCILER ADD VERSIYON INT NOT NULL DEFAULT 1
GO

ALTER TABLE OGRENCILER ADD OLUSTURMATARIHI DATETIME NOT NULL DEFAULT GETDATE()
GO

ALTER TABLE OGRENCILER ADD DUZENLEMETARIHI DATETIME NULL 
GO

INSERT INTO OGRENCILER
VALUES('OGRENCI2','SOYISIM2','18265789','1998-02-26',
'MAMAK',NULL,NULL,1)
GO


UPDATE OGRENCILER
SET ANNEADI = 'Ayþe',
    BABAADI = 'Ali',
    DUZENLEMETARIHI = GETDATE()
WHERE ID = 2


SELECT * FROM OGRENCILER

INSERT INTO OGRENCILER(ADI,SOYADI,OGRENCINO,DOGUMTARIHI,DOGUMYERI,DURUMU)
VALUES('OGRENCI3','SOYISIM3','45524499','2001-05-30','YENIMAHALLE',1)
GO

DROP TABLE OGRENCILER -- TABLOYU SILER



ALTER TABLE OGRENCILER ADD BUKOLONFAZLA INT

ALTER TABLE OGRENCILER ALTER COLUMN BUKOLONFAZLA
SMALLINT
GO --BUKOLONFAZLA Kolonunun tipini degistirdi



--ALTER TABLE OGRENCILER RENAME COLUMN BUKOLONFAZLA TO BUKOLONYENIADI
--GO


--KOLON ADINI DEGISTIRME
EXEC sp_rename 'dbo.OGRENCILER.BUKOLONFAZLA','BUKOLONYENIADI','COLUMN'
GO


--KOLONU KALICI SILME
ALTER TABLE OGRENCILER DROP COLUMN BUKOLONYENIADI


--TABLONUN ADINI DEGISTIRME
EXEC sp_rename 'dbo.OGRENCILER', 'OGRENCILERYENI'
GO



SELECT * FROM OGRENCILERYENI




--TABLONUN ICINDEKÝ VERILERI SILER
DELETE FROM dbo.OGRENCILERYENI
-- DIKKAT !!
-- ID Sifirlanmaz yeni gelen uye en son kalan ID'den devam edecektýr


--TABLONUN ICINDEKÝ VERILERI SILER
TRUNCATE TABLE dbo.OGRENCILERYENI

--ANCAK ID de sifirlanir



