Create Database ORNEKDB Collate Turkish_CS_AS
Go

Use ORNEKDB
Go

Create Table ORNEKTABLE_1(
 ID int,
 ADI nvarchar(25),
 SOYADI nvarchar(25),
 YAS int,
 SEHIR nvarchar(50)
)

ALTER TABLE ORNEKTABLE_1 ALTER COLUMN ADI NVARCHAR(50) NOT NULL
ALTER TABLE ORNEKTABLE_1 ALTER COLUMN SOYADI NVARCHAR(50) NOT NULL

--UNIQUE ID
Create Table ORNEKTABLE_3(
 ID int UNIQUE,
 ADI nvarchar(25),
 SOYADI nvarchar(25),
 YAS int,
 SEHIR nvarchar(50)
)

--1KEZ CALISACAK, SONRASINDA ID UNIQUE LIGINDEN DOLAYI CALISMAZ 2 DEFA NULL ALAMAZ
INSERT INTO ORNEKTABLE_3 (ADI,SOYADI)
VALUES ('BURAK','GONCA')

--UNIQUE LIGI KALDIRMAK ICIN;
ALTER TABLE ORNEKTABLE_3 DROP CONSTRAINT UQ__ORNEKTAB__3214EC2663C745A3

--UNIQUE ID ' LIGI TABLO OLUSTURURKEN VERMEK
Create Table ORNEKTABLE_4(
 ID int,
 ADI nvarchar(25),
 SOYADI nvarchar(25),
 YAS int,
 SEHIR nvarchar(50),
 CONSTRAINT UQ_ID UNIQUE(ID)
)


CREATE TABLE SIPARISLER(
 ID INT PRIMARY KEY IDENTITY, --DEFAULT (1,1)
 SIPARISTARIHI DATETIME NOT NULL,
 SIPARISNO NVARCHAR(10) NOT NULL,
 MUSTERI_ID INT
)


CREATE TABLE MUSTERILER(







----------------------------------------------------------------------------------------


CREATE DATABASE SINEMADB
GO

USE SINEMADB

CREATE TABLE FILMLER(
FILMID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(30) NOT NULL,
ACIKLAMA NVARCHAR(50) NULL,
ONSEKIZYASUSTUMU BIT NULL, -- (0-EVET,1-HAYIR)
FILMFK INT,
CONSTRAINT FK_FILMER_YONETMENLER_1_N FOREIGN KEY (FILMFK) REFERENCES YONETMENLER (YONETMENID)
)

CREATE TABLE OYUNCULAR(
OYUNCUID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(25) NOT NULL,
SOYAD NVARCHAR(25) NOT NULL
)

CREATE TABLE KATEGORILER(
KATEGORIID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(25) NOT NULL
)

CREATE TABLE YONETMENLER(
YONETMENID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(25) NOT NULL,
SOYAD NVARCHAR(25) NOT NULL,
)

CREATE TABLE KULLANICI(
KULLANICIID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(25) NOT NULL,
SOYAD NVARCHAR(25) NOT NULL,
ONSEKIZYASUSTUMU BIT NULL -- (0-EVET,1-HAYIR)
)

CREATE TABLE FK_FILMLER_OYUNCULAR(
FILMFK INT FOREIGN KEY REFERENCES FILMLER(FILMID),
OYUNCUFK INT FOREIGN KEY REFERENCES OYUNCULAR(OYUNCUID)
)

CREATE TABLE FK_FILMLER_KATEGORILER(
FILMTURLERIID INT PRIMARY KEY IDENTITY,
FILMFK INT FOREIGN KEY REFERENCES FILMLER(FILMID),
OYUNCUFK INT FOREIGN KEY REFERENCES OYUNCULAR(OYUNCUID)
)

CREATE TABLE FK_FILMLER_KULLANICILAR_YORUM(
YORUMID INT PRIMARY KEY IDENTITY,
FILMFK INT FOREIGN KEY REFERENCES FILMLER(FILMID),
KULLANICIFK INT FOREIGN KEY REFERENCES KULLANICI(KULLANICIID)
)

CREATE TABLE FK_FILMLER_KULLANICILAR_FAVORI(
FAVORIID INT PRIMARY KEY IDENTITY,
FILMFK INT FOREIGN KEY REFERENCES FILMLER(FILMID),
KULLANICIFK INT FOREIGN KEY REFERENCES KULLANICI(KULLANICIID)
)



--------------------------------------------------------------------------------



CREATE DATABASE KUTUPHANEDB
GO

USE KUTUPHANEDB
GO

CREATE TABLE KITAPLAR(
KITAPID INT PRIMARY KEY IDENTITY,
KITAPADI NVARCHAR(25) NOT NULL,
KITAPTURU NVARCHAR(50) NULL,
KATEGORILERFK INT,
SALONLARFK INT,
CONSTRAINT FK_SALONLAR_KITAPLAR_1_N FOREIGN KEY (SALONLARFK) REFERENCES SALONLAR (SALONID),
CONSTRAINT FK_KATEGORILER_KITAPLAR_1_N FOREIGN KEY (KATEGORILERFK) REFERENCES KATEGORILER (KATEGORIID)
)

SELECT * FROM KITAPLAR

CREATE TABLE SALONLAR(
SALONID INT PRIMARY KEY IDENTITY,
SALONNO CHAR(2) NOT NULL
)

CREATE TABLE KATEGORILER(
KATEGORIID INT PRIMARY KEY IDENTITY,
KATEGORIADI NVARCHAR(25) NOT NULL,
ONSEKIZYASUSTUMU BIT NULL --(0-EVET/1-HAYIR)
)

CREATE TABLE KULLANICILAR(
KULLANICIID INT PRIMARY KEY IDENTITY,
KULLANICIADI NVARCHAR(25) NOT NULL,
KULLANICISOYADI NVARCHAR(25) NOT NULL
)


CREATE TABLE ODUNCKITAPLAR(
ODUNCKITAPID INT PRIMARY KEY IDENTITY,
ODUNCKITAPADI NVARCHAR(25) NOT NULL,
ODUNCDURUMU BIT NULL, -- (0-ODUNCTE/1-GERIVERILDI)
KULLANICILARFK INT,
CONSTRAINT FK_KULLANICILAR_ODUNCKITAPLAR_1_N FOREIGN KEY (KULLANICILARFK) REFERENCES KULLANICILAR(KULLANICIID)
)



--------------------------------------------------------------------------------------------------

--INNER JOIN KULLANIMI


USE Northwind
GO

--HER URUNU KATEGORI ISMI ILE BIRLIKTE GOSTER

SELECT * FROM Urunler AS U INNER JOIN Kategoriler AS K
 ON U.KategoriID = K.KategoriID

 SELECT * FROM URUNLER
 SELECT * FROM Kategoriler



 --BIR PERSONELIN YAPTIGI SATISI YAPTIGI MUSTERI ISMI VE TARIHI ILE BIRLIKTE GOSTER
 --PERSONEL>>PID
 --SATIS>>PID(FK),MID(FK),SID
 --MUSTERI>>MID

 SELECT P.Adi,M.MusteriAdi,S.SatisTarihi FROM Personeller AS P INNER JOIN Satislar AS S
  ON P.PersonelID = S.PersonelID
  INNER JOIN Musteriler AS M ON M.MusteriID = S.MusteriID



   --JANET PERSONELININ SATISLARININ BILGISINI GOSTER
  SELECT P.Adi,M.MusteriAdi,S.SatisTarihi FROM Personeller AS P INNER JOIN Satislar AS S
  ON P.PersonelID = S.PersonelID
  INNER JOIN Musteriler AS M ON M.MusteriID = S.MusteriID
  WHERE P.Adi = 'Janet' 



  --JANET PERSONELININ 'PAULA PARENTE' ADLI MUSTERISINE YAPTIGI SATISLARIN BILGISINI GOSTER
  SELECT P.Adi,M.MusteriAdi,S.SatisTarihi FROM Personeller AS P INNER JOIN Satislar AS S
  ON P.PersonelID = S.PersonelID
  INNER JOIN Musteriler AS M ON M.MusteriID = S.MusteriID
  WHERE P.Adi = 'Janet' and m.MusteriAdi = 'Paula Parente'





